parent_cfg: configs/credsplatting/dtu_pretrain.yaml
exp_name: dtu_ft_scan1
credsplatting:
    test_input_views: 4
train_dataset:
    scene: scan1
test_dataset:
    scene: scan1
train:
    epoch: 233 # pretrained epoch +10
save_ep: 1
eval_ep: 1
