parent_cfg: configs/credsplatting/dtu_pretrain.yaml

train_dataset_module: lib.datasets.colmap.credsplatting
test_dataset_module: lib.datasets.colmap.credsplatting

credsplatting:
    eval_center: True
    reweighting: True
    scale_factor: 1
    cas_config:
        render_if: [False, True]
        volume_planes: [64, 8]

train_dataset:
    data_root: 'datasets/Frames_S1'
    split: 'train'
    input_h_w: [480, 480]
    input_ratio: 1.
    scene: ''

test_dataset:
    data_root: 'datasets/Frames_S1'
    split: 'test'
    input_h_w: [480, 480]
    input_ratio: 1.
    scene: ''

