parent_cfg: configs/credsplatting/dtu_pretrain.yaml

train_dataset_module: lib.datasets.tnt.credsplatting
test_dataset_module: lib.datasets.tnt.credsplatting

credsplatting:
    eval_center: True
    reweighting: True
    scale_factor: 500
    test_input_views: 3
    cas_config:
        render_if: [False, True]
        volume_planes: [64, 8]

train_dataset:
    data_root: '../datasets/tnt'
    split: 'train'
    input_h_w: [640, 960]
    input_ratio: 1.

test_dataset:
    data_root: '../datasets/tnt'
    split: 'test'
    input_h_w: [640, 960]
    input_ratio: 1.
