parent_cfg: configs/credsplatting/llff_eval.yaml
exp_name: llff_ft_trex

credsplatting:
    test_input_views: 4
    train_input_views: [3, 4]
    train_input_views_prob: [0.4, 0.6]
    cas_config:
        render_if: [True, True]
train_dataset:
    scene: trex
test_dataset:
    scene: trex
train:
    epoch: 252 # pretrained epoch +10
    lr: 5e-4
ep_iter: 1000
save_ep: 1
eval_ep: 1
